
project_id = "uqfbhtpvmrchstleswxr"
[functions.create-checkout]
verify_jwt = true
[functions.send-email]
verify_jwt = false
[functions.scheduled-tasks]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
