// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqfbhtpvmrchstleswxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZmJodHB2bXJjaHN0bGVzd3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDMxMTIsImV4cCI6MjA2MzE3OTExMn0.yTa4N-bsijT7JTuqWrDfoklYUgsIQNDZAH4EfQm3HiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);